Repository ynput/ayon-equalizer, pull requests merged in 2025-01, with the labels that each got.

#17 Fix linting reported by ruff workflow/validation
  client/ayon_equalizer/__init__.py
  client/ayon_equalizer/api/__init__.py
Labels: type: maintenance

#12 Fix camera offset
  client/ayon_equalizer/plugins/publish/extract_lens_distortion_nuke.py
  client/ayon_equalizer/plugins/publish/extract_matchmove_script_maya.py
  client/ayon_equalizer/plugins/publish/extract_matchmove_script_nuke.py
Labels: type: bug, community

#11 Open latest workfile hook
  client/ayon_equalizer/hooks/pre_add_last_workfile_arg.py
Labels: type: enhancement, community
